#!/usr/bin/env python3
# This is free and unencumbered software released into the public domain.
# For more information, please refer to <http://unlicense.org/>
"""Generate bench_frame.h: a deterministic synthetic analysis frame.

The cycle-count benchmark must feed *identical* input to every build so that
the only thing that varies between optimization levels is the generated code,
not the data. We therefore precompute one representative frame here and embed
it as a flash-resident const array, rather than synthesizing it on-target with
libm (whose code would itself change shape across -O levels).

The frame is a 220 Hz (A3) sawtooth-like tone: a strong fundamental with a 1/h
harmonic rolloff, scaled to ~90% of the 12-bit single-ended ADC range. This
exercises both pitch paths on a realistic, octave-correction-relevant signal.
"""
import math

FRAME_SIZE = 1024      # keep in sync with src/config.h
SAMPLE_FREQ = 4096     # keep in sync with src/config.h
F0 = 220.0             # A3
NHARM = 8
FULL_SCALE = 2047      # 12-bit single-ended, +-2048

weights = [1.0 / h for h in range(1, NHARM + 1)]
norm = 0.9 * FULL_SCALE / sum(weights)

samples = []
for n in range(FRAME_SIZE):
    s = 0.0
    for h in range(1, NHARM + 1):
        if F0 * h < SAMPLE_FREQ / 2.0:
            s += weights[h - 1] * math.sin(2.0 * math.pi * F0 * h * n / SAMPLE_FREQ)
    v = int(round(norm * s))
    v = max(-2048, min(2047, v))
    samples.append(v)

with open("bench_frame.h", "w") as f:
    f.write("/* Generated by gen_frame.py -- do not edit by hand. */\n")
    f.write("/* 220 Hz (A3) sawtooth-like tone, 8 harmonics, ~90%% full scale. */\n")
    f.write("#ifndef BENCH_FRAME_H_\n#define BENCH_FRAME_H_\n\n")
    f.write("#include <stdint.h>\n\n")
    f.write(f"#define BENCH_FRAME_SIZE {FRAME_SIZE}\n")
    f.write(f"#define BENCH_F0_HZ {F0:.1f}\n\n")
    f.write("static const int16_t BENCH_FRAME[BENCH_FRAME_SIZE] = {\n")
    for i in range(0, FRAME_SIZE, 12):
        row = ", ".join(f"{v:6d}" for v in samples[i:i + 12])
        f.write("    " + row + ",\n")
    f.write("};\n\n#endif /* BENCH_FRAME_H_ */\n")

print(f"wrote bench_frame.h ({FRAME_SIZE} samples, f0={F0} Hz)")
