#!/usr/bin/env bash
# This is free and unencumbered software released into the public domain.
# For more information, please refer to <http://unlicense.org/>
#
# profile_stages.sh -- per-stage cycle breakdown of each pitch path.
#
# Builds the bench_profile.c harness with -DTUNA_PROFILE (so the PROFILE_MARK()
# markers in src/yin.c and src/spectral.c are active), runs it under simavr via
# simprof, and prints the cycles spent in each DSP stage. The profiling target
# is the atmega1284p (classic AVRe+ core, as for the other cycle benchmarks), so
# numbers are a consistent relative breakdown, not absolute avr64dd14 timing.
set -u

HERE="$(cd "$(dirname "$0")" && pwd)"
SRC="$HERE/../src"
OUT="$HERE/out"
RESULTS="$HERE/profile.md"
MCU="atmega1284p"
mkdir -p "$OUT"

# ---- stage names, keyed "<from>-<to>" (see PROFILE_MARK ids in the sources) -
declare -A YIN_NAME=(
    [1-2]="difference + CMND + threshold"  [2-3]="fallback min search"
    [3-4]="parabolic interp"               [4-255]="return + tail"
)
declare -A FFT_NAME=(
    [1-2]="DC removal + prescale"  [2-3]="windowing"  [3-4]="real-input pack"
    [4-5]="FFT transform"   [5-6]="magnitude split"  [6-7]="peak pick"
    [7-8]="octave correct"  [8-9]="parabolic interp" [9-255]="return + tail"
)

# ---- build simprof if needed ----------------------------------------------
if [ ! -x "$HERE/simprof" ] || [ "$HERE/simprof.c" -nt "$HERE/simprof" ]; then
    gcc -O2 -Wall "$HERE/simprof.c" -o "$HERE/simprof" -lsimavr || exit 1
fi
[ -f "$HERE/bench_frame.h" ] || ( cd "$HERE" && python3 gen_frame.py )

# ---- profile one method ----------------------------------------------------
# $1 = method macro, $2 = display name, $3 = name of the assoc array
profile() {
    local method="$1" name="$2" arrname="$3" elf="$OUT/prof_$2.elf"
    local extra="" dsp
    if [ "$method" = "PITCH_METHOD_FFT" ]; then
        extra="-DBENCH_FFT"; dsp="$SRC/spectral.c $SRC/fft.c $SRC/window.c"
    else
        dsp="$SRC/yin.c"
    fi
    avr-gcc -mmcu="$MCU" -Os -flto -funsigned-char -funsigned-bitfields \
        -DTUNA_PROFILE $extra -I"$SRC" -I"$HERE" -DF_CPU=16000000UL -D"$method" \
        "$HERE/bench_profile.c" $dsp -o "$elf" -lm 2>"$OUT/prof_$2.log" || {
        echo "build failed for $name (see $OUT/prof_$2.log)"; return 1; }

    # Collect transitions, total = sum of stage cycles. simavr prints "Loaded
    # ..." banners to stdout; keep only well-formed "<id>\t<id>\t<cycles>" rows.
    local tsv; tsv="$("$HERE/simprof" "$elf" "$MCU" 2>/dev/null \
        | awk -F'\t' 'NF==3 && $1 ~ /^[0-9]+$/ && $3 ~ /^[0-9]+$/')"
    local total; total="$(awk -F'\t' '{s+=$3} END{print s}' <<<"$tsv")"

    echo
    echo "### $name path  (total ${total} cycles)"
    echo
    printf '| stage | cycles | %% of total |\n'
    printf '|-------|-------:|-----------:|\n'
    local from to cyc key nm
    while IFS=$'\t' read -r from to cyc; do
        [ -z "$from" ] && continue
        key="${from}-${to}"
        nm="$(eval "echo \"\${${arrname}[$key]:-stage $key}\"")"
        awk -v n="$nm" -v c="$cyc" -v t="$total" \
            'BEGIN{printf "| %-22s | %6d | %9.1f%% |\n", n, c, 100*c/t}'
    done <<<"$tsv"
}

{
    echo "# Per-stage DSP cycle profile"
    echo
    echo "_Generated by \`bench/profile_stages.sh\`. Fixed 220 Hz frame, \`-Os -flto\`,"
    echo "simavr on \`$MCU\` (classic AVRe+ core -- relative breakdown, not absolute Dx timing)._"
    profile "PITCH_METHOD_YIN" "YIN" YIN_NAME
    profile "PITCH_METHOD_FFT" "FFT" FFT_NAME
} | tee "$RESULTS"

echo
echo "Wrote $RESULTS"
