#!/usr/bin/env bash
# This is free and unencumbered software released into the public domain.
# For more information, please refer to <http://unlicense.org/>
#
# sweep.sh -- YIN accuracy-vs-cost sweep.
#
# YIN is the default pitch method and its cost is ~100% the difference loop
# (see profile_stages.sh), whose work is O(YIN_W * YIN_TAU_MAX). This sweeps
# those two knobs and, for each setting, pairs:
#   * accuracy -- pitch error in cents over a 30..1000 Hz synthetic corpus,
#                 from sweep_yin.c built on the host (bit-identical fixed point);
#   * cost     -- DSP cycles from bench_dsp.c under simavr (atmega1284p).
# so you can pick a setting on the speed/range frontier rather than by guess.
set -u

HERE="$(cd "$(dirname "$0")" && pwd)"
SRC="$HERE/../src"
OUT="$HERE/out"
RESULTS="$HERE/sweep.md"
MCU="atmega1284p"
BUDGET=6000000          # 250 ms @ 24 MHz
mkdir -p "$OUT"

if [ ! -x "$HERE/simrun" ] || [ "$HERE/simrun.c" -nt "$HERE/simrun" ]; then
    gcc -O2 -Wall "$HERE/simrun.c" -o "$HERE/simrun" -lsimavr || exit 1
fi
[ -f "$HERE/bench_frame.h" ] || ( cd "$HERE" && python3 gen_frame.py )

# accuracy line: "<mean> <p95> <max> <gross> <count> <lowest_ok_hz>"
accuracy() { # $1=tau_max $2=w
    gcc -std=c11 -O2 -I"$SRC" -I"$HERE" -DYIN_TAU_MAX="$1" -DYIN_W="$2" \
        "$HERE/sweep_yin.c" "$SRC/yin.c" -o "$OUT/acc.elf" -lm 2>/dev/null \
        && "$OUT/acc.elf" || echo "ERR ERR ERR ERR ERR ERR"
}

# DSP cycles for the same knobs.
cycles() { # $1=tau_max $2=w
    avr-gcc -mmcu="$MCU" -Os -flto -funsigned-char -funsigned-bitfields \
        -DPITCH_METHOD_YIN -DYIN_TAU_MAX="$1" -DYIN_W="$2" \
        -I"$SRC" -I"$HERE" -DF_CPU=16000000UL \
        "$HERE/bench_dsp.c" "$SRC/yin.c" -o "$OUT/sweep.elf" -lm 2>/dev/null \
        && "$HERE/simrun" "$OUT/sweep.elf" "$MCU" 2>/dev/null \
             | awk '/^[0-9]+$/{n=$0} END{print (n==""?"ERR":n)}' \
        || echo ERR
}

row() { # $1=tau_max $2=w $3=default-marker
    local tau="$1" w="$2" mark="$3"
    read med p95 gross cnt low <<<"$(accuracy "$tau" "$w")"
    local cyc; cyc="$(cycles "$tau" "$w")"
    local floor pct
    floor="$(awk -v s="$SAMPLE_FREQ_VAL" -v t="$tau" 'BEGIN{printf "%.1f", s/t}')"
    pct="$(awk -v c="$cyc" -v b="$BUDGET" 'BEGIN{printf "%.0f%%", 100*c/b}')"
    printf '| %4s%s | %4s | %s | %s | %s | %s | %s | %s | %s |\n' \
        "$tau" "$mark" "$w" "$floor" "$cyc" "$pct" "$med" "$p95" "$gross" "$low"
}

# SAMPLE_FREQ for the freq-floor column (read from config.h).
SAMPLE_FREQ_VAL="$(awk '/define +SAMPLE_FREQ/{gsub(/[^0-9]/,"",$3); print $3}' "$SRC/config.h")"

{
    echo "# YIN accuracy vs. cost sweep"
    echo
    echo "_Generated by \`bench/sweep.sh\`. Accuracy: |error| in cents over a"
    echo "30..1000 Hz corpus (pure / harmonic-rich / weak-fundamental). Cost: DSP"
    echo "cycles under simavr on \`$MCU\` (relative, not absolute Dx timing)._"
    echo
    echo "Detection floor = SAMPLE_FREQ / YIN_TAU_MAX; tones below it cannot be"
    echo "found and show up as gross (>50 cent) misses. Frame budget = $BUDGET cycles."
    echo
    echo "## Vary YIN_TAU_MAX (YIN_W = 512, the default)"
    echo
    printf '| tau_max | YIN_W | floor Hz | cycles | %% budget | median\|c\| | p95\|c\| | gross | lowest ok Hz |\n'
    printf '|--------:|------:|---------:|-------:|---------:|--------:|------:|------:|-------------:|\n'
    for tau in 96 128 160 192 256 320; do
        m=""; [ "$tau" = 160 ] && m=" *"
        row "$tau" 512 "$m"
    done
    echo
    echo "## Vary YIN_W (YIN_TAU_MAX = 160, the default)"
    echo
    printf '| tau_max | YIN_W | floor Hz | cycles | %% budget | median\|c\| | p95\|c\| | gross | lowest ok Hz |\n'
    printf '|--------:|------:|---------:|-------:|---------:|--------:|------:|------:|-------------:|\n'
    for w in 256 384 512; do
        m=""; [ "$w" = 512 ] && m=" *"
        row 160 "$w" "$m"
    done
    echo
    echo "_\`*\` marks the shipped defaults (YIN_TAU_MAX=160, YIN_W=512). \"lowest"
    echo "ok Hz\" is the lowest swept tone still within 50 cents._"
} | tee "$RESULTS"

echo
echo "Wrote $RESULTS"
